### ISSUE TITLE
When is the release planned for?

### ISSUE THREAD

**Issue by reynoldscem** [XT-1997/DeepMatcher#1]
Would be great to be able to evaluate the method.

**Comment by XT-1997** [comment]
The paper is currently in the first peer review, and the plan is to open the source code when the second manuscript is submitted, which may take some time. Please wait patiently.

**Comment by XT-1997** [comment]
The paper is currently in the first peer review, and the plan is to open the source code when the revised manuscript is submitted, which may take some time. Please wait patiently.
